export const WOD_CATEGORIES = {
  girls: { label: "The Girls", accent: "#2E7D32", text: "#6fcf7f", bg: "#1a3a2a" },
  hero: { label: "Hero WODs", accent: "#FF6B35", text: "#ffa070", bg: "#2d1f0f" },
  strength: { label: "Strength & Other", accent: "#2E86AB", text: "#6fb8d9", bg: "#1a2e3d" },
  competition: { label: "Competition", accent: "#A23B72", text: "#d17aaf", bg: "#2d1a2d" },
};

export const BENCHMARK_WODS = [
  // === The Girls ===
  {
    id: "fran",
    name: "Fran",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "21-15-9 reps for time:\n- Thrusters (43/30 kg)\n- Pull-ups",
  },
  {
    id: "grace",
    name: "Grace",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "30 clean and jerks for time (61/43 kg)",
  },
  {
    id: "isabel",
    name: "Isabel",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "30 snatches for time (61/43 kg)",
  },
  {
    id: "helen",
    name: "Helen",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "3 rounds for time:\n- 400m run\n- 21 KB swings (24/16 kg)\n- 12 pull-ups",
  },
  {
    id: "diane",
    name: "Diane",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "21-15-9 reps for time:\n- Deadlifts (102/70 kg)\n- Handstand push-ups",
  },
  {
    id: "elizabeth",
    name: "Elizabeth",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "21-15-9 reps for time:\n- Squat cleans (61/43 kg)\n- Ring dips",
  },
  {
    id: "nancy",
    name: "Nancy",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "5 rounds for time:\n- 400m run\n- 15 overhead squats (43/30 kg)",
  },
  {
    id: "annie",
    name: "Annie",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "50-40-30-20-10 reps for time:\n- Double unders\n- Sit-ups",
  },
  {
    id: "karen",
    name: "Karen",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "150 wall balls for time (9/6 kg to 3m/2.7m target)",
  },
  {
    id: "jackie",
    name: "Jackie",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "For time:\n- 1000m row\n- 50 thrusters (20/15 kg)\n- 30 pull-ups",
  },
  {
    id: "amanda",
    name: "Amanda",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "9-7-5 reps for time:\n- Muscle-ups (ring)\n- Squat snatches (61/43 kg)",
  },
  {
    id: "cindy",
    name: "Cindy",
    category: "girls",
    scoreType: "rounds_reps",
    timeCap: 20,
    description: "20 min AMRAP:\n- 5 pull-ups\n- 10 push-ups\n- 15 air squats",
  },
  {
    id: "mary",
    name: "Mary",
    category: "girls",
    scoreType: "rounds_reps",
    timeCap: 20,
    description: "20 min AMRAP:\n- 5 handstand push-ups\n- 10 single-leg squats (alternating)\n- 15 pull-ups",
  },
  {
    id: "barbara",
    name: "Barbara",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "5 rounds for time (3 min rest between rounds):\n- 20 pull-ups\n- 30 push-ups\n- 40 sit-ups\n- 50 air squats",
  },
  {
    id: "linda",
    name: "Linda",
    category: "girls",
    scoreType: "time",
    timeCap: null,
    description: "10-9-8-7-6-5-4-3-2-1 reps for time:\n- Deadlift (1.5x bodyweight)\n- Bench press (bodyweight)\n- Clean (0.75x bodyweight)",
  },
  // === Hero WODs ===
  {
    id: "murph",
    name: "Murph",
    category: "hero",
    scoreType: "time",
    timeCap: null,
    description: "For time (with 9/6 kg weight vest):\n- 1 mile run\n- 100 pull-ups\n- 200 push-ups\n- 300 air squats\n- 1 mile run\n(Partition pull-ups, push-ups, and squats as needed)",
  },
  {
    id: "dt",
    name: "DT",
    category: "hero",
    scoreType: "time",
    timeCap: null,
    description: "5 rounds for time:\n- 12 deadlifts (70/47.5 kg)\n- 9 hang power cleans (70/47.5 kg)\n- 6 push jerks (70/47.5 kg)",
  },
  {
    id: "the-chief",
    name: "The Chief",
    category: "hero",
    scoreType: "rounds_reps",
    timeCap: null,
    description: "5 x 3 min AMRAP (1 min rest between):\n- 3 power cleans (61/43 kg)\n- 6 push-ups\n- 9 air squats\nScore: total rounds + reps across all 5 cycles",
  },
  // === Strength & Other ===
  {
    id: "crossfit-total",
    name: "CrossFit Total",
    category: "strength",
    scoreType: "load",
    timeCap: null,
    description: "Sum of 3 lifts (1RM each):\n- Back squat\n- Shoulder press\n- Deadlift\nScore: total weight (kg)",
  },
  {
    id: "filthy-fifty",
    name: "The Filthy Fifty",
    category: "strength",
    scoreType: "time",
    timeCap: null,
    description: "For time:\n- 50 box jumps (61/51 cm)\n- 50 jumping pull-ups\n- 50 KB swings (16/12 kg)\n- 50 walking lunge steps\n- 50 knees-to-elbows\n- 50 push presses (20/15 kg)\n- 50 back extensions\n- 50 wall ball shots (9/6 kg)\n- 50 burpees\n- 50 double unders",
  },
  {
    id: "fight-gone-bad",
    name: "Fight Gone Bad",
    category: "strength",
    scoreType: "reps",
    timeCap: null,
    description: "3 rounds for total reps (1 min each station, 1 min rest between rounds):\n- Wall balls (9/6 kg to 3m/2.7m target)\n- Sumo deadlift high pulls (34/25 kg)\n- Box jumps (51/51 cm)\n- Push presses (34/25 kg)\n- Row (calories)",
  },
];

export const COMPETITION_WODS_PRELOADED = [
  {
    id: "open-24-1",
    name: "Open 24.1",
    category: "competition",
    scoreType: "time",
    timeCap: 15,
    description: "For time (15 min cap):\n21-15-9 each arm:\n- DB snatches (22.5/15 kg)\n- Burpees over DB\n(Complete all snatches on one arm, then burpees, then switch arms)",
  },
  {
    id: "open-24-2",
    name: "Open 24.2",
    category: "competition",
    scoreType: "reps",
    timeCap: 20,
    description: "20 min AMRAP:\n- 30-stroke row\n- 10 deadlifts (102/70 kg)\n- 50 double unders",
  },
  {
    id: "open-24-3",
    name: "Open 24.3",
    category: "competition",
    scoreType: "time",
    timeCap: 18,
    description: "For time (18 min cap):\n5 rounds of:\n- 10 thrusters (43/29 kg)\n- 10 chest-to-bar pull-ups\nThen, 3 rounds of:\n- 8 thrusters (61/43 kg)\n- 8 bar muscle-ups",
  },
];
